### ISSUE TITLE
Uncommented Lines in probe block cause error

### ISSUE THREAD

**Issue by LucidityCrash** [top-gun/Klipper4V-Core#2]
https://github.com/top-gun/Klipper4V-Core/blob/413e5f77cd158f0324709a7e0038b15275e45813/vcore3/sensorless-homing/printer.cfg#L191-L243

You've commented out the rest of the [probe] section meaning the 2 uncommened lines 
`samples: 3`
and
`samples_tolerance: 0.02`
are seen as part of the [input_shaper] block and are invalid there causing an error

**Comment by top-gun** [comment]
Thank you, fixed :)
